#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'mcp'

# Run the Misoca CLI with provided arguments
MCP::Client::Misoca::CLI.new.run(ARGV)
